additional prescription endpoint test
noharm-ai/backend pull request #347
Opened 2024-08-06 19:42 UTC by rubensmau

2024-08-06 20:24 UTC, rubensmau commented
In my machine the tests are successful. Is the database used in these tests  updated?

2024-08-06 23:46 UTC, marceloarocha commented
@rubensmau 
Yep! they are updated. It looks like the coverage report is failing. Don't worry about that for now. You can keep going 👍

2024-08-08 19:30 UTC, marceloarocha requested changes
Excelente!! Pode passar estes 2 casos de teste para um novo arquivo, por favor? test_conciliation.py

2024-08-08 19:30 UTC, marceloarocha commented on tests/test_prescription.py
> +        .filter(Prescription.id == 9199)
pode colocar o 9199 em uma variável, assim não precisa repetir o mesmo número.

2024-08-09 14:40 UTC, closed without merging